name: dependency quality

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  schedule:
    - cron: '41 6 * * 1'
  workflow_dispatch:

permissions: {}

jobs:
  quality:
    uses: ./.github/workflows/quality-callable.yml
    permissions:
      contents: read
