name: release

on:
  push:
    branches: [main]

concurrency:
  group: release-${{ github.repository_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  release:
    uses: ./.github/workflows/release-callable.yml
    secrets: inherit
    permissions:
      actions: read
      contents: write
      security-events: write
